apiVersion: v1
clusters:
- cluster:
    certificate-authority: C:\Users\andrizan\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Wed, 07 Dec 2022 13:14:43 +07
        provider: minikube.sigs.k8s.io
        version: v1.28.0
      name: cluster_info
    server: https://127.0.0.1:56724
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Wed, 07 Dec 2022 13:14:43 +07
        provider: minikube.sigs.k8s.io
        version: v1.28.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: C:\Users\andrizan\.minikube\profiles\minikube\client.crt
    client-key: C:\Users\andrizan\.minikube\profiles\minikube\client.key
